name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    inputs:
      myname:
        description: "what is your name?"
        required: true
jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        run: python script.py ${{ github.event.inputs.myname }}
