name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    inputs:
      myname:
        description: "what is your name?"
        required: true
jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - run: python3 ../../script.py
