name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run"
        default: true
        type: boolean
      api-key:
        description: "API key of the tenant"
        required: true
      stage:
        description: "latest/beta/test/prod/parvati"
        type: choice
        options:
          - latest
          - beta
          - test
          - prod
          - parvati
      blocks:
        description: "delete blocks"
        type: boolean
      exclude-blocks:
        description: "blocks to exclude from deletion"
        type: string
      deployments:
        description: "delete deployments (Leave empty if you do not want to delete blocks)"
        type: boolean
      exclude-deployments:
        description: "deployments to exclude from deletion"
        type: string

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout to repo"
        uses: actions/checkout@v4

      - name: "Run script"
        run: echo 'y' | python script.py --name ${{ github.event.input.stage }} --age 15
