name: Tenant housekeeping
run-name: ${{ github.actor }} is cleaning up the tenant resources
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run"
        type: boolean
        default: true
      api-key:
        description: "API key of the tenant"
        type: string
        required: true
      stage:
        description: "latest/beta/test/prod/parvati"
        type: choice
        options:
          - latest
          - beta
          - test
          - prod
          - parvati
      blocks:
        description: "delete blocks"
        type: boolean
      exclude-blocks:
        description: "blocks to exclude from deletion"
        type: string
      deployments:
        description: "delete deployments (Leave empty if you do not want to delete blocks)"
        type: boolean
      exclude-deployments:
        description: "deployments to exclude from deletion"
        type: string

jobs:
  start:
    name: Start Clean up
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout to repo"
        uses: actions/checkout@v4

      - name: "Run script"
        run: echo 'y' | python script.py --api-key ${{ github.event.inputs.api-key }} --stage ${{ github.event.inputs.stage }} ${{ github.event.inputs.dry-run && '--dry-run' || '' }} ${{ github.event.inputs.blocks && '--blocks + github.event.inputs.exclude-blocks' || '' }} ${{ github.event.inputs.deployments == true && '--deployments + github.event.inputs.exclude-deployments' || '' }}
